"""Shared limits for the AstraQPU serial protocol."""

PROTOCOL = "astraqpu.serial.v0"

MAX_JSON_LINE_BYTES = 4096
MAX_JOB_ID_CHARS = 48
MAX_INSTRUCTIONS = 256
MAX_REGISTER_NAME_CHARS = 48
MAX_REGISTER_VALUE_CHARS = 96
MAX_DEVICE_EVENT_NAME_CHARS = 48
MAX_DEVICE_OP_CHARS = 24
MAX_TRACE_EVENTS = 4096

